import type { AppState } from '../../src/core/types';

export const defaultState: AppState = {
  tool: 'select',
  city: 'krasnodar',
  panel: 1,
  inverter: 1,
  orientation: 'portrait',
  gap: 0.05,
  margin: 0.4,
  tilt: 45,
  azimuth: 180,
  consumption: 450,
  selfUse: 60,
  tariff: 6.5,
  exportRate: 2.5,
  project: 'Тестовый проект',
  batteryEnabled: false,
  battery: 0,
  reserve: 20,
  financing: 'cash',
  down: 30,
  rate: 18,
  termMonths: 60,
  showShadows: true,
  shadeMonth: 6,
  shadeHour: 12,
  shadeLoss: new Array(12).fill(0),
  orth: true,
  roof: [],
  panels: [],
  obstacles: [],
  tempRoof: [],
  bg: {
    visible: false,
    opacity: 0.5,
    calibS: 0,
  },
};
